### ISSUE TITLE
House is Down, but net worth is positive?

### ISSUE THREAD

**Issue by MappingKat** [MappingKat/issues#15]
http://www.homebotapp.com/homes/5789-Pioneer-Mesa-Dr-80923/56b5091366f6a0bb2552a916?preview=1

http://www.homebotapp.com/homes/2681-S-Holman-St-80228/56b508cf50bc20b9259bd3be?preview=1

Wording is a little confusing.  Net worth is positive but the house price is down?
<img width="605" alt="screenshot 2016-02-07 21 56 50" src="https://cloud.githubusercontent.com/assets/1077436/12878650/c2e8b81a-cde5-11e5-822a-3a8d87e16379.png">

**Comment by imcmahon** [comment]
So net worth is basically how much your home is worth minus how much you still owe. Since most mortgages require at least some downpayment, the net is still positive in these cases.

`avmValue` : $252,089
`-` `outstandingPrincipal` : $246,703
`=` `netWorth` or `equity` : $5,386

![image](https://cloud.githubusercontent.com/assets/70205/12892219/53e3f246-ce48-11e5-9f6f-3f81fc6f51f3.png)

**Comment by MappingKat** [comment]
Ah!  I think that makes sense when you look at your own home and know the numbers.  Im going to close this.
